### PR TITLE
Update to contributing file and creating PR template

### PR DESCRIPTION
**Pull request by jaels**
This is a link to the template: 
https://github.com/OpenKnowledgeMaps/headstart-vue/blob/dev/docs/pull_request_template.md

### CODE REVIEW

**Comment by jaels** [comment]
Hey,
1. About the templates for contributers - I already did that a while ago - it's in the ISSUE_TEMPLATE folder in the repo - https://github.com/OpenKnowledgeMaps/headstart-vue/tree/dev/.github/ISSUE_TEMPLATE. I thought you wanted also a checklist for PR reviewers. Do you? 
2. Sorry about the design goals, not sure what happened there, but now its the right file.

**Comment by jaels** [comment]
Hey,
I changed the template, have a look - https://github.com/OpenKnowledgeMaps/headstart-vue/edit/dev/docs/pull_request_template.md
And added a link to it in the CONTRIBUTION file.

Let me know what you think.

**Comment by pkraker** [comment]
Thanks, the template looks very good! I think that the only task left is to add the rest of the content from the GDoc to the CONTRIBUTING file and fix the typo in the file name and we should be good to go!

**Comment by jaels** [comment]
Added all the fixes

**Comment by tarrow** [comment]
Closed, I took the changes described in the title of the PR out and added them as c360dabe30183921094949a914240062bd751ecc Still credited to @jaels

**Pull request closed without merging**
