### PR TITLE
All changes from Dev to Master

### PR DESCRIPTION
**Pull request by tarrow**
Once big change after our initial setup. This should be merged in place of all the previously agreed PRs.

Any more changes will be merged with the following procedure:
- PR to Dev
- 1st level reviewer approves and merges PR to dev
- 1st level reviewer opens PR to master from commit on dev
- 2nd level reviewer approves PR to master

### CODE REVIEW

**Comment by pkraker** [comment]
Thanks! I assume that this is what I should be seeing when I run it?
screenshot

**Comment by pkraker** [comment]
BTW, is `npm run serve --fix` the suggested command to build and run the dev server? Otherwise, I am getting hundreds of warnings and errors related to line endings (probably because I am running AutoCrlf on my Windows machine).

**Comment by rbachleitner** [comment]
I can look into it on my windows install, but on Linux `npm run serve` did fine.

**Comment by rbachleitner** [comment]
And yes, that is what you should see.

**Comment by pkraker** [comment]
Excellent, thanks! Will merge this now.

**Pull request merged**
